[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"

# Enable Netlify Identity
[template.environment]
  NETLIFY_IDENTITY = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
